### ISSUE TITLE
Create a staking dashboard

### ISSUE THREAD

**Issue by justinbarry** [burnt-labs/xion.js#12]
# Problem
No current method exists to allow for users to stake using.
# Solution
There are two directions to go here. First, implement AA in Cosmoskit (Which will happen at some point). Alternatively, a dashboard can be created an Cosmoskit can be swapped out for the Abstraxion library. 

# Relevant
- [Tutorial](https://cosmology.tech/learn/video/staking-dashboard) on creating a staking dashboard

**Comment by rio0606** [comment]
oghey

**Comment by justinbarry** [comment]
Finished.
