### ISSUE TITLE
Abstraxion Library Updates for V2

### ISSUE THREAD

**Issue by justinbarry** [burnt-labs/xion.js#14]
# Description
To support the new authz based design the Abstraxion library's behavior must change. When the "connect" hook is invoked the following must happen:

- [x] Check for an existing keypair in local memory
    - [x] If a keypair exists, check for active authz grants
- [x] Generate Private key/public key pair
- [x] In the current tab, show the modal below
- [x] Open a new tab with the public key (passed in the URL along with the requested AuthZ privileges. See #16 )
    - [ ] The URL must be configurable
- [x] Poll in the background for a the authz grants, when granted, hide modal and show as connected.
- [x] The "Try again" link should attempt to reopen the new tab

# Design
[Figma Design](https://www.figma.com/file/X8jw1LYWh73W2osMSReH7x/Account-Abstraction?type=design&node-id=632-571&mode=design&t=KqtkSoNTi5lTy254-4)
<img width="1468" alt="image" src="https://github.com/burnt-labs/xion.js/assets/328965/7d192ee7-79bd-4928-ac64-3dcde156b9d6">

**Comment by rio0606** [comment]
nice
