### ISSUE TITLE
Abstraxion Account dashboard Updates V2

### ISSUE THREAD

**Issue by justinbarry** [burnt-labs/xion.js#15]
# Description
The account dashboard is going to take on a lot of the features of the previous version of Abstraxion. Most of the code that existed in the Abstraxion library will be moving into the dashboard project.

- [x] Migrate Login views into the account dashboard (This could be into a new package)
- [ ] Create route which looks for passed in public keys and [authz permissions](#16 ) in URL
    - [ ] If present, show permission dialog in design below (Assuming the user is logged in, if not put them in the login flow first)
    - [ ] If accepted, craft and submit a transaction granting the requested permissions to the passed public key  

# Decisions to be made
- [ ] Do we need to pass in a project specific icon? If not, what does a generic one look like?
- [ ] Can we show the referrer/opener URL in the dialog? Is this spoofable?

# Design
## Permission dialog
[Figma Design](https://www.figma.com/file/X8jw1LYWh73W2osMSReH7x/Account-Abstraction?type=design&node-id=632-1294&mode=design&t=oxXulPinr82BTQFL-4)
<img width="1456" alt="image" src="https://github.com/burnt-labs/xion.js/assets/328965/51345245-5c25-43ba-84fa-8f0beae600a3">

**Comment by rio0606** [comment]
done
