### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by dalechyn** [burnt-labs/xion.js#172]
I'll list potential issues that might be causing the overall SDK unreliability that I'd recommend to get fixed.

### Critical
`AbstraxionAuth` contains asynchronous logic in it's constructor. As constructors are synchronous by nature, this may lead to issues when expecting fields that are set in asynchronous call are expected to be set, while promise to set them is still resolving.
https://github.com/burnt-labs/xion.js/blob/d528c33e51ca2a469c04e818cb33c04633d8aa9d/packages/abstraxion-core/src/AbstraxionAuth.ts#L32-L56
Recommendation: Make constructor private and create an asynchronous static `create` or `initialize` function to retrieve an instance of this class.

----

`openDashboardTab` tries to alert in a `window`-less environment.
[`alert`](https://developer.mozilla.org/en-US/docs/Web/API/Window/alert) is an instance of `window`, there fore it will always fail if it's `undefined`.
https://github.com/burnt-labs/xion.js/blob/d528c33e51ca2a469c04e818cb33c04633d8aa9d/packages/abstraxion-core/src/AbstraxionAuth.ts#L191-L218
Recommendation: replace it with `console.log` or else.

### Code smell
`getLocalKeypair` doesn't simply gets a keypair but also sets it on an instance. 
https://github.com/burnt-labs/xion.js/blob/d528c33e51ca2a469c04e818cb33c04633d8aa9d/packages/abstraxion-core/src/AbstraxionAuth.ts#L89-L99
Recommendation: don't mutate state in getters and mutate it elsewhere.

## `abstraxion` package

General concern is that this package doesn't use the logic from `abstraxion-core` that actually already implements the polling for a granter, managing localstorage etc, but reimplements everything. Are there any blockers to re-use existing logic opposed to repeating it twice?

Examples:
- localStorage mutations
https://github.com/burnt-labs/xion.js/blob/d528c33e51ca2a469c04e818cb33c04633d8aa9d/packages/abstraxion-core/src/AbstraxionAuth.ts#L84-L86
  
  https://github.com/burnt-labs/xion.js/blob/d528c33e51ca2a469c04e818cb33c04633d8aa9d/packages/abstraxion/src/components/AbstraxionSignin/index.tsx#L29-L32

- Polling (which currently is the pain point for me). While the same effect is intended, the logic is actually different.
https://github.com/burnt-labs/xion.js/blob/d528c33e51ca2a469c04e818cb33c04633d8aa9d/packages/abstraxion-core/src/AbstraxionAuth.ts#L221-L295
  https://github.com/burnt-labs/xion.js/blob/d528c33e51ca2a469c04e818cb33c04633d8aa9d/packages/abstraxion/src/components/AbstraxionSignin/index.tsx#L86-L125

### Critical
`isConnecting` might hang in `true` status if `configureAccount` throws an error.
https://github.com/burnt-labs/xion.js/blob/d528c33e51ca2a469c04e818cb33c04633d8aa9d/packages/abstraxion/src/hooks/useAbstraxionAccount.ts#L28-L51
Recommendation: wrap with try catch and finally.

**Comment by justinbarry** [comment]
Thank you for your input! We were able to implement most of this [here](https://github.com/burnt-labs/xion.js/pull/174/).
