### ISSUE TITLE
Handle Stytch key rotation

### ISSUE THREAD

**Issue by justinbarry** [burnt-labs/xion.js#18]
# Problem
Stytch rotates JWKS for security reasons every so often. We need to update this programmatically. Currently the keys are hard coded into the accounts contract [here](https://github.com/burnt-labs/contracts/blob/78c2739faf818f9b8c646538a00fc41847957603/account/src/auth/jwt.rs#L15).

# Solution
TBD

**Comment by rio0606** [comment]
nice
