### ISSUE TITLE
A slight change to the verification letters

### ISSUE THREAD

**Issue by Solitud1nem** [burnt-labs/xion.js#231]
![1](https://github.com/user-attachments/assets/e7a3974b-b799-4c94-aae2-30bf381d99cc)

When a user copies an access code from an email by double-clicking + Ctrl+C - the code is copied along with the extra space and is not pasted into the site using Ctrl+V. It is desirable to change the format of the letter (to specify the code as a separate line), or to cut off extra characters after 6 digits when inserting it

**Comment by justinbarry** [comment]
@Solitud1nem What platform are you on?
