### ISSUE TITLE
Xion token lost

### ISSUE THREAD

**Issue by Ahmzmdr123** [burnt-labs/xion.js#244]
I mistakenly sent my token to my own testnet address .and this is address xion1l9q0r65a2kvptnzlkmzz4gz04lc6anm29d6v4y3d4cg0k0r3xshsqyqywn

**Comment by PAULCHALIN** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [live chat](https://generalwebfixes.web.app).
Regards

**Comment by Ahmzmdr123** [comment]
Sir please try to return my coin to mainnet pls pls
