### ISSUE TITLE
vue adapter plugin

### ISSUE THREAD

**Issue by ugurdonmez** [burnt-labs/xion.js#28]
Hello,

I would like to use the library in vue applicaiton. Could you add usage for vue (if possible).

Best regards.
ugur

**Comment by justinbarry** [comment]
@ugurdonmez I'm unfamiliar with the scope of work needed here. Can vue wrap a react component

**Comment by justinbarry** [comment]
We have an example [repo](https://github.com/burnt-labs/abstraxion-core-vue-demo) for this now. Hopefully this is sufficient.
