### ISSUE TITLE
Error Screen Design

### ISSUE THREAD

**Issue by justinbarry** [burnt-labs/xion.js#30]
Description
---
While working on [the implementation](https://github.com/burnt-labs/xion.js/issues/14) of the new V2 designs we noticed there is a need for a Error condition design. 

Solution
---
Please design an error condition model and attach to this ticket.

**Comment by BurntDisco** [comment]
Here is the link to the error page design.

https://www.figma.com/file/X8jw1LYWh73W2osMSReH7x/Account-Abstraction?type=design&node-id=821%3A18308&mode=design&t=LJDHzLc9JBwYXcVQ-1

**Comment by BurntVal** [comment]
Implemented.

**Comment by rio0606** [comment]
belum ada
