### ISSUE TITLE
Abstraxion V2 Docs

### ISSUE THREAD

**Issue by justinbarry** [burnt-labs/xion.js#31]
- [x] Update our [current walkthrough](https://docs.burnt.com/xion/develop/featured-guides/build-react-dapp-with-account-abstraxion)
- [x] Replace workflow diagram [here](https://docs.burnt.com/xion/develop/featured-guides/build-react-dapp-with-account-abstraxion/meta-accounts-design)
- [x] Include examples of different grants that can be requested from the Dapp side

**Comment by rio0606** [comment]
nice
