### ISSUE TITLE
Automatically select modal updates

### ISSUE THREAD

**Issue by justinbarry** [burnt-labs/xion.js#4]
<img width="513" alt="image" src="https://github.com/burnt-labs/abstraxion/assets/328965/11f97c74-02d7-4649-af52-f01fa4898fd2">

- [ ] Select first account if only one exists
- [ ] Upon selecting an account in the modal, the modal should close.

**Comment by justinbarry** [comment]
Irrelevant with [V2](https://github.com/burnt-labs/xion.js/issues/11)

**Comment by rio0606** [comment]
ok
