### ISSUE TITLE
Guild - connecting wallet

### ISSUE THREAD

**Issue by CryptoFrostyWalker** [burnt-labs/xion.js#46]
Hi, 

I tried to connect my MetaMask wallet at Guild, but when I click on that I sent my requesto of approval on Coinbase wallet. Tried few different options, but couldn't. Not sure if I'm the only one, but would be nice to work out especially now, when a lot of people are connecting on Guild

Hope it will help to solve the problem

**Comment by rio0606** [comment]
nice project

**Comment by justinbarry** [comment]
I believe this has been forwarded to the Guild team. Reach out in the discord if you are still having trouble, lots of awesome folk about to help you
