### ISSUE TITLE
Can't read contract information in explorer

### ISSUE THREAD

**Issue by script-money** [burnt-labs/xion.js#48]
This address is demo-app contract address, but show as a baseAccount
https://explorer.burnt.com/xion-testnet-1/account/xion1z70cvc08qv5764zeg3dykcyymj5z6nu4sqr7x8vl4zjef2gyp69s9mmdka

**Comment by justinbarry** [comment]
Hey @script-money! By demo app address, you mean you created it in the demo app? Where did you find this address in the UI?

**Comment by script-money** [comment]
> Hey @script-money! By demo app address, you mean you created it in the demo app? Where did you find this address in the UI?

What I mean is that even when I enter a contract address in the blockchain browser, it still appears as a base account address.

**Comment by justinbarry** [comment]
@script-money That is correct, contracts show as BaseAccounts in the explorer.
