### ISSUE TITLE
Automatically create first account if none exists

### ISSUE THREAD

**Issue by justinbarry** [burnt-labs/xion.js#6]
This screen should only appear if multiple smart accounts exists for a particular authenticator.

<img width="486" alt="image" src="https://github.com/burnt-labs/abstraxion/assets/328965/c6f94cb7-a2f3-455b-a3db-da392a6d85e1">

If no accounts exists for an authenticator, we need to enter the create flow directly without clicking.
If one account exists, it should appear as normal authenticated.

**Comment by justinbarry** [comment]
Irrelevant with [V2](https://github.com/burnt-labs/xion.js/issues/11).

**Comment by rio0606** [comment]
belum ada
