### ISSUE TITLE
Dapp "Connected" screen updates

### ISSUE THREAD

**Issue by justinbarry** [burnt-labs/xion.js#64]
Add account information in the dapp connected modal along with some other style adjustments.

[Design](https://www.figma.com/file/X8jw1LYWh73W2osMSReH7x/Account-Abstraction?type=design&node-id=1022%3A19349&mode=design&t=5IfcIvNp8peZMo3Y-1)

**Comment by Adelmiloudi21** [comment]
How  to connect my wallet xion to node The necessary orders for it
