### ISSUE TITLE
Docker based local development setup

### ISSUE THREAD

**Issue by justinbarry** [burnt-labs/xion.js#8]
- [x] burnt-labs/xion.js#7
- [x] https://github.com/burnt-labs/xion-indexer/issues/3
- [x] https://github.com/burnt-labs/xion/issues/145
- [x] https://github.com/burnt-labs/xion-indexer/issues/4
- [x] https://github.com/burnt-labs/account-abstraction-api/issues/4
- [x] https://github.com/burnt-labs/xion/issues/141

**Comment by rio0606** [comment]
nice

**Comment by justinbarry** [comment]
Closing, will work on the defining the local development story later
