### ISSUE TITLE
Need to augment dashboard grant screen with a list of contract addresses and token amounts

### ISSUE THREAD

**Issue by justinbarry** [burnt-labs/xion.js#84]
The dapp can now request the following grants (permissions):
```typescript
[
  "CONTRACT_ADDRESS",
  {
    address: "CONTRACT_ADDRESS_WHICH_NEEDS_TO_MOVE_FUNDS",
    amounts: [{ denom: "uxion", amount: "1000000" }],
  },
],
```
We need to add this information to this screen:
<img width="559" alt="image" src="https://github.com/burnt-labs/xion.js/assets/328965/63a1b3db-c1b8-441d-9279-f4d697638d25">

**Comment by BurntDisco** [comment]
Adding design here

https://www.figma.com/file/X8jw1LYWh73W2osMSReH7x/Account-Abstraction?type=design&node-id=1177%3A3718&mode=design&t=MmOTFVcgZ34uw6AX-1
