### ISSUE TITLE
Immediate Iterations

### ISSUE THREAD

**Issue by BurntVal** [burnt-labs/xion.js#9]
This list is for immediate iterations to be done for the abstraxion repo. The order of this list does not signify priority or importance.

As of 11-13-23:
- [ ] Update docs
- [ ]  Refactor keplr/metamask connect buttons to adjust to device 
(use mobile wallets vs browser extensions)
- [ ]  Add additional hooks 
(might wait for dev feedback on which functionalities they'd like)
- [ ]  Add modal open status to context with setState so it can be opened from anywhere in the app 
(good for cases where devs want to force a signin from multiple places)
- [ ]  implement a "click outside" hook so the modal behaves as expected
- [ ]  Refactor graz connections to use abstract accounts
Can be as easy as passing graz 'offlineSigner' into `AAClient.connectWithSigner(...)`
Need to get a consensus of what this looks like before diving in

**Comment by justinbarry** [comment]
Irrelevant with https://github.com/burnt-labs/xion.js/issues/11.

**Comment by rio0606** [comment]
nano nyet
